// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketAppWeb.Models.DataLayer;

#nullable disable

namespace TicketAppWeb.Migrations
{
    [DbContext(typeof(TicketAppContext))]
    partial class TicketAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketAppWeb.Models.Number", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Numbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Value = 82.0
                        },
                        new
                        {
                            Id = 3,
                            Value = 33.0
                        },
                        new
                        {
                            Id = 4,
                            Value = 400.0
                        },
                        new
                        {
                            Id = 5,
                            Value = 65.0
                        },
                        new
                        {
                            Id = 6,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 7,
                            Value = 720.0
                        },
                        new
                        {
                            Id = 8,
                            Value = 90.0
                        },
                        new
                        {
                            Id = 9,
                            Value = 23.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
